#########################################################
## 'Validate module with PSRule' Composite Action      ##
#########################################################
##
## This composite action contains the logic to validate a module using a set of PSRule tests
##
#########################################################
##
##-------------------------------------------##
## ACTION PARAMETERS                         ##
##-------------------------------------------##
##
##   |==================================================================================================================================================|
##   | Parameter                | Required | Default | Description                          | Example                                                   |
##   |--------------------------|----------|---------|--------------------------------------|-----------------------------------------------------------|
##   | moduleTestFilePath       | true     | ''      | The path to the module PSRule tests. | 'utilities/pipelines/staticValidation/module.tests.ps1'   |
##   | subscriptionId           | false    | ''      | The subscriptionId to deploy to      | '1a97b80a-4dda-4f50-ab53-349e29344654'                    |
##   | managementGroupId        | false    | ''      | The managementGroupId to deploy to   | '1a97b80a-4dda-4f50-ab53-349e29344654'                    |
##   |==================================================================================================================================================|
##
##---------------------------------------------##

name: 'Execute PSRule module tests'
description: 'Execute PSRule module tests (if any)'

inputs:
  moduleTestFilePath:
    description: 'The path to the test file'
    required: true
    default: ''
  subscriptionId:
    description: 'The subscription ID to deploy to'
    required: false
  managementGroupId:
    description: 'The management group ID to deploy to'
    required: false

runs:
  using: 'composite'
  steps:
    # [Module PSRule Test] task(s)
    #-----------------------------
    - name: 'Replace tokens in template file'
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $templateFilePath = '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}'
          # Grouping task logs
          Write-Output '::group::Replace tokens in template file'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'tokensReplacement' 'Convert-TokensInFileList.ps1')

          # Populate tokens
          $Tokens = @{
            resourceGroupName = '${{ env.resourceGroupName }}'
            subscriptionId    = '${{ inputs.subscriptionId }}'
            managementGroupId = '${{ inputs.managementGroupId }}'
            tenantId          = '${{ env.ARM_TENANT_ID }}'
          }

          ## Add local (source control) tokens
          $tokenMap = @{}
          foreach ($token in (Get-ChildItem env: | Where-Object -Property Name -Like "localToken_*")) {
            $tokenMap += @{ $token.Name.Replace('localToken_','','OrdinalIgnoreCase') = $token.value }
          }
          Write-Verbose ('Using local tokens [{0}]' -f ($tokenMap.Keys -join ', ')) -Verbose
          $Tokens += $tokenMap

          ## Swap 'namePrefix' token if empty and provided as a GitHub secret
          if([String]::IsNullOrEmpty($Tokens['namePrefix'])){
            Write-Verbose 'Using [namePrefix] token from GitHub' -Verbose
            $Tokens['namePrefix'] = '${{ env.TOKEN_NAMEPREFIX }}'
          }

          # Construct Token Function Input
          $ConvertTokensInputs = @{
            FilePathList = @($templateFilePath)
            Tokens       = $Tokens
            TokenPrefix  = '${{ env.tokenPrefix }}'
            TokenSuffix  = '${{ env.tokenSuffix }}'
          }

          Write-Verbose "Convert Tokens Input:`n $($ConvertTokensInputs | ConvertTo-Json -Depth 10)" -Verbose

          # Invoke Token Replacement Functionality [For Module]
          $null = Convert-TokensInFileList @ConvertTokensInputs

          Write-Output '::endgroup::'

    # Run analysis by using the PSRule GitHub action.
    - name: Run PSRule analysis
      uses: microsoft/ps-rule@v2.4.0
      # continue-on-error: true # Setting this whilst PSRule gets bedded in, in this project
      with:
        modules: 'PSRule.Rules.Azure'
        inputPath: '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}'
        outputFormat: Csv
        outputPath: '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}-output.csv'

    - name: 'Set PSRule Output'
      if: always()
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          # Grouping task logs
          Write-Output '::group::Setting Output'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'PSRuleValidation' 'Set-PSRuleOutput.ps1')

          # Populate tokens
          $Input = @{
            inputFilePath = '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}-output.csv'
            outputFilePath = '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}-output.md'
          }

          Write-Verbose "Set PS Rule Output with following parameters:`n $($Input | ConvertTo-Json -Depth 10)" -Verbose

          # Invoke Set PSRule Output Functionality
          $null = Set-PSRuleOutput @Input

          Write-Output '::endgroup::'

    - name: Output to Github summaries
      shell: bash
      if: always()
      run: cat '${{ env.modulePath }}/${{ inputs.moduleTestFilePath }}-output.md' >> $GITHUB_STEP_SUMMARY
